name: Setup Node.js

runs:
  using: "composite"
  steps:
    - uses: buildjet/setup-node@v3
      with:
        node-version: 18.18.2
        registry-url: 'https://registry.npmjs.org'
    - run: corepack enable
      shell: bash