name: Release CLI and packages

on:
  workflow_dispatch:
  release:
    types: [published]

env:
  NODE_ENV: production

jobs:
  release:
    runs-on: buildjet-4vcpu-ubuntu-2204
    permissions:
      contents: write
    concurrency:
      group: release-cli
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-node
      - name: Install node_modules
        uses: ./.github/actions/install
        with:
          fail-on-cache-miss: false

      - name: Upload and release CLI
        working-directory: ./cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          ADMIN_ACCESS_TOKEN: ${{ secrets.ADMIN_ACCESS_TOKEN }}
        run: |
          ./scripts/publishToNPM.js || true

